//AnimationVideoHero
//EventPageHero
//ManagedServicesHero
//GalleryPageHero
//CoWorkingPageHero
//IndividualManagedServicesHero
//ProjectDeliveryPageHero
//OurModelPageHero
//PortfoliosandTeamPageHero
